#!/bin/bash

# TLP Optimizer - Optimize Linux laptop battery life through TLP configuration
# Copyright (C) 2025 Dacraezy1
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# Created by: Dacraezy1
# Creation Date: 2025-11-03 15:01:48 UTC

# Colors for better readability
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Function to print colored text
print_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

# Function to check if running as root
check_root() {
    if [ "$EUID" -ne 0 ]; then 
        print_error "Please run as root"
        exit 1
    fi
}

# Function to detect CPU driver
detect_cpu_driver() {
    if [ -d "/sys/devices/system/cpu/intel_pstate" ]; then
        echo "intel_pstate"
    elif [ -d "/sys/devices/system/cpu/amd_pstate" ]; then
        echo "amd_pstate"
    else
        echo "acpi-cpufreq"
    fi
}

# Function to detect GPU
detect_gpu() {
    local gpu_info=""
    if lspci | grep -i nvidia > /dev/null; then
        gpu_info="nvidia"
    elif lspci | grep -i amd | grep -i vga > /dev/null; then
        gpu_info="amd"
    elif lspci | grep -i intel | grep -i vga > /dev/null; then
        gpu_info="intel"
    fi
    echo "$gpu_info"
}

# Function to get battery health
get_battery_health() {
    if ! command -v upower &> /dev/null; then
        echo "unknown"
        return
    fi

    local battery_path
    battery_path=$(upower -e | grep 'BAT')
    if [ -z "$battery_path" ]; then
        echo "no_battery"
        return
    fi

    local energy_full energy_full_design health
    energy_full=$(upower -i "$battery_path" | awk '/energy-full:/ {print $2}')
    energy_full_design=$(upower -i "$battery_path" | awk '/energy-full-design:/ {print $2}')

    if [ -n "$energy_full" ] && [ -n "$energy_full_design" ]; then
        health=$(awk "BEGIN {printf \"%.2f\", ($energy_full/$energy_full_design)*100}")
        echo "$health"
    else
        echo "unknown"
    fi
}

# Function to detect storage type
detect_storage() {
    if [ -n "$(lsblk -d -o name,rota | awk '$2==0 {print $1}')" ]; then
        echo "ssd"
    else
        echo "hdd"
    fi
}

# Main function to generate TLP configuration
generate_tlp_config() {
    local cpu_driver="$1"
    local gpu_type="$2"
    local storage_type="$3"
    local battery_health="$4"

    # Create config file
    cat > /etc/tlp.conf << EOF
# tlp.conf generated by tlp-optimizer
# Generated on: $(date)

# Enable TLP
TLP_ENABLE=1
TLP_DEFAULT_MODE=BAT

# CPU Settings
CPU_SCALING_GOVERNOR_ON_AC=performance
CPU_SCALING_GOVERNOR_ON_BAT=powersave

# CPU driver specific settings
EOF

    # CPU driver specific settings
    case "$cpu_driver" in
        "intel_pstate")
            cat >> /etc/tlp.conf << EOF
CPU_SCALING_MIN_FREQ_ON_AC=800000
CPU_SCALING_MAX_FREQ_ON_AC=3500000
CPU_SCALING_MIN_FREQ_ON_BAT=800000
CPU_SCALING_MAX_FREQ_ON_BAT=2300000
CPU_ENERGY_PERF_POLICY_ON_AC=performance
CPU_ENERGY_PERF_POLICY_ON_BAT=power
CPU_HWP_ON_AC=performance
CPU_HWP_ON_BAT=power
EOF
            ;;
        "amd_pstate")
            cat >> /etc/tlp.conf << EOF
CPU_SCALING_MIN_FREQ_ON_AC=800000
CPU_SCALING_MAX_FREQ_ON_AC=3500000
CPU_SCALING_MIN_FREQ_ON_BAT=800000
CPU_SCALING_MAX_FREQ_ON_BAT=2300000
PLATFORM_PROFILE_ON_AC=performance
PLATFORM_PROFILE_ON_BAT=low-power
EOF
            ;;
        "acpi-cpufreq")
            cat >> /etc/tlp.conf << EOF
CPU_SCALING_MIN_FREQ_ON_AC=800000
CPU_SCALING_MAX_FREQ_ON_AC=3500000
CPU_SCALING_MIN_FREQ_ON_BAT=800000
CPU_SCALING_MAX_FREQ_ON_BAT=2300000
EOF
            ;;
    esac

    # GPU Settings
    case "$gpu_type" in
        "nvidia")
            cat >> /etc/tlp.conf << EOF

# NVIDIA GPU Settings
RUNTIME_PM_DRIVER_BLACKLIST=nvidia
RUNTIME_PM_ON_AC=on
RUNTIME_PM_ON_BAT=auto
EOF
            ;;
        "amd")
            cat >> /etc/tlp.conf << EOF

# AMD GPU Settings
RADEON_DPM_STATE_ON_AC=performance
RADEON_DPM_STATE_ON_BAT=battery
RADEON_POWER_PROFILE_ON_AC=high
RADEON_POWER_PROFILE_ON_BAT=low
EOF
            ;;
        "intel")
            cat >> /etc/tlp.conf << EOF

# Intel GPU Settings
INTEL_GPU_MIN_FREQ_ON_AC=300
INTEL_GPU_MIN_FREQ_ON_BAT=300
INTEL_GPU_MAX_FREQ_ON_AC=1200
INTEL_GPU_MAX_FREQ_ON_BAT=800
INTEL_GPU_BOOST_FREQ_ON_AC=1200
INTEL_GPU_BOOST_FREQ_ON_BAT=900
EOF
            ;;
    esac

    # Storage settings
    if [ "$storage_type" = "ssd" ]; then
        cat >> /etc/tlp.conf << EOF

# SSD Settings
SATA_LINKPWR_ON_AC=max_performance
SATA_LINKPWR_ON_BAT=min_power
DISK_IOSCHED=mq-deadline
DISK_APM_LEVEL_ON_AC=254
DISK_APM_LEVEL_ON_BAT=128
EOF
    else
        cat >> /etc/tlp.conf << EOF

# HDD Settings
DISK_APM_LEVEL_ON_AC=254
DISK_APM_LEVEL_ON_BAT=128
DISK_SPINDOWN_TIMEOUT_ON_AC=0
DISK_SPINDOWN_TIMEOUT_ON_BAT=120
EOF
    fi

    # Battery health based settings
    if [ "$battery_health" != "unknown" ] && [ "$battery_health" != "no_battery" ]; then
        local battery_threshold
        if (( $(echo "$battery_health < 75" | bc -l) )); then
            battery_threshold=85
        else
            battery_threshold=95
        fi
        cat >> /etc/tlp.conf << EOF

# Battery Settings
START_CHARGE_THRESH_BAT0=$battery_threshold
STOP_CHARGE_THRESH_BAT0=96
EOF
    fi
}

# Main script execution
main() {
    check_root

    print_info "TLP Optimizer - Interactive Configuration Generator"
    echo "======================================================"

    # Detect and confirm CPU driver
    local detected_cpu_driver
    detected_cpu_driver=$(detect_cpu_driver)
    print_info "Detected CPU driver: $detected_cpu_driver"
    read -p "Is this correct? (Y/n/specify different): " cpu_response
    cpu_response=${cpu_response:-Y}
    if [[ $cpu_response =~ ^[Nn]$ ]]; then
        echo "Please specify CPU driver (intel_pstate/amd_pstate/acpi-cpufreq): "
        read detected_cpu_driver
    fi

    # Detect and confirm GPU
    local detected_gpu
    detected_gpu=$(detect_gpu)
    print_info "Detected GPU: $detected_gpu"
    read -p "Is this correct? (Y/n/specify different): " gpu_response
    gpu_response=${gpu_response:-Y}
    if [[ $gpu_response =~ ^[Nn]$ ]]; then
        echo "Please specify GPU (nvidia/amd/intel): "
        read detected_gpu
    fi

    # Detect and confirm storage type
    local detected_storage
    detected_storage=$(detect_storage)
    print_info "Detected storage type: $detected_storage"
    read -p "Is this correct? (Y/n/specify different): " storage_response
    storage_response=${storage_response:-Y}
    if [[ $storage_response =~ ^[Nn]$ ]]; then
        echo "Please specify storage type (ssd/hdd): "
        read detected_storage
    fi

    # Get battery health
    local battery_health
    battery_health=$(get_battery_health)
    if [ "$battery_health" != "unknown" ] && [ "$battery_health" != "no_battery" ]; then
        print_info "Battery health: ${battery_health}%"
    else
        print_info "Battery health: $battery_health"
    fi

    # Backup existing configuration
    if [ -f "/etc/tlp.conf" ]; then
        print_info "Backing up existing configuration..."
        cp /etc/tlp.conf "/etc/tlp.conf.backup.$(date +%Y%m%d_%H%M%S)"
    fi

    # Generate new configuration
    print_info "Generating TLP configuration..."
    generate_tlp_config "$detected_cpu_driver" "$detected_gpu" "$detected_storage" "$battery_health"

    # Apply configuration
    print_info "Applying new configuration..."
    systemctl restart tlp

    print_success "TLP configuration has been generated and applied!"
    print_info "Configuration file: /etc/tlp.conf"
    print_info "Backup of old configuration (if existed) was created"
}

# Run main function
main
